FROM node:16
WORKDIR /app
RUN npm install -g @nestjs/cli
COPY package.json ./
RUN npm install --force
COPY . .
RUN npm run build
ENV PORT=3335
# NAME
ENV PROJECT_NAME = "Salary-Backend"
# APP
ENV TZ=UTC
ENV NODE_ENV=development
ENV APP_URL=http://104.248.48.180
ENV APP_PORT=3335
ENV UI_APP_URL=http://104.248.48.180:3333
# DATABASE
ENV DATABASE_USER=salary
ENV DATABASE_PASSWORD=salary123
ENV DATABASE_URL=postgres://salary:salary123@104.248.48.180:5432/salary
# AUTH
ENV JWT_TOKEN_KEY=PakBw6WxqD
ENV JWT_EXPIRES_IN=7d
ENV EMAIL_JWT_EXPIRES_IN=23h
# AWS CLOUDWATCH
ENV AWS_ACCESS_KEY=
ENV AWS_KEY_SECRET=
ENV CLOUDWATCH_GROUP_NAME=
ENV CLOUDWATCH_STREAM_NAME=
ENV CLOUDWATCH_AWS_REGION=
ENV ENVIRONMENT=staging
RUN npm run seed
EXPOSE 3335
CMD [ "npm", "run" , "start:prod" ]